paths:
  /api/products:
    get:
      summary: Retorna una lista de productos
      tags:
        - Productos
      description: Este endpoint trae la lista de productos del ecommerce
      responses:
        "200":
          description: JSON array de nombres de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "404":
          description: Error
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              