export const ERROR_TYPES = {
  TIPO_DE_DAROS: 400,
  ARGUMENTOS_INVALIDOS: 400,
  AUTENTICATION: 401,
  AUTORIZACION: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};

export default ERROR_TYPES;